### ISSUE TITLE
Exporting blocks is faulty (found in Mac OS)

### ISSUE THREAD

**Issue by maprzybylla** [edutec/Snap4Arduino#41]
I cannot export blocks and then import them later. However, exporting and importing projects works. I found out that the xml file that is created when exporting a project does have character encoding, while the one that is created when blocks are exported doesn't.
Also, when exporting a project I'm asked where to store the file. When I export blocks, I'm just shown the xml document tree and have to create the file myself.

**Comment by bromagosa** [comment]
Fixed now :)

I'm gonna push the releases to the project page.

**Comment by maprzybylla** [comment]
Wooohooooo! Thanks a lot, you are awesome! My students will be more than happy to hear this! :o)

**Comment by bromagosa** [comment]
Thanks to you for reporting it, I'm sorry I haven't tackled this earlier... we've been terribly busy these months!

(you can get the new version from the project page already)
