### ISSUE TITLE
Snap4Arduino+I2C+1602LCD

### ISSUE THREAD

**Issue by cccczl** [edutec/Snap4Arduino#44]
Snap4Arduino+I2C+1602LCD How do？

**Comment by bromagosa** [comment]
@cccczl We have written a tutorial on how to control additional devices by modifying firmata:

http://blog.s4a.cat/2015/03/13/Extending-Firmata-for-Snap4Arduino.html

We're working on a LCD-capable firmata, I'll let you know when it's ready :)

**Comment by bromagosa** [comment]
@cccczl there you go: http://blog.s4a.cat/2015/03/24/LCD-Library-for-Snap4Arduino.html

I'm closing this now :)
