### ISSUE TITLE
Doubt: Only one script in the project can handle the connected board?

### ISSUE THREAD

**Issue by SnapSitin** [edutec/Snap4Arduino#53]
Hi !

I have just started to work with snap4arduino.

I have done a project with several sprites but when I try to handle the board from different sprites it seems that only one of them can be associated with arduino board at a time... the one on which the programmer runs the "Connect arduino" block.

Is that the intended behaviour or it is a bug?

In the first case I encourage you to allow sharing the board by all the sprites... otherwise the logic
of  these projects will always to fix a sprite as the "monitor board" and manages the communcation
with the other sprites by means of messages...

thanks in advance

**Comment by bromagosa** [comment]
Hi!

The logic behind this behaviour is that it allows you to use as many boards as you wish at the same time. Each sprite can handle a board, and this keeps it consistent with the way everything else works in Snap.

If you want to trigger behaviours in "remote" sprites, you should follow the same techniques you'd use in Snap itself, that is: messages.

For instance, in the Sprite that holds the connection with your board:

![gas](https://cloud.githubusercontent.com/assets/1016697/6936641/c0c52dca-d854-11e4-9338-16a4a7efc8e1.png)

And in another Sprite:

![gas](https://cloud.githubusercontent.com/assets/1016697/6936657/ea868bae-d854-11e4-8b83-ac7911406d39.png)
