### ISSUE TITLE
Uncaught node.js Error when download extra costumes

### ISSUE THREAD

**Issue by nuzza412** [edutec/Snap4Arduino#56]
Hi there,

I would like to report a bug in the software. Whenever I try to download some extra costumes this "Uncaught node.js Error" comes out. Please see the screenshot for further information.
Many thanks
![screen shot 2015-04-29 at 11 25 08](https://cloud.githubusercontent.com/assets/7326814/7389105/d090784e-ee62-11e4-8b49-722707155248.png)

**Comment by bromagosa** [comment]
Hi @nuzza412, thanks for the report!

How are you trying to import these costumes? Drag and drop?

**Comment by nuzza412** [comment]
Hi @bromagosa I tried to use the drop down menu. Please see the attachment.
![screen shot 2015-04-29 at 12 01 23](https://cloud.githubusercontent.com/assets/7326814/7389621/8cba2dea-ee67-11e4-9431-22ec4da29f25.png)

**Comment by bromagosa** [comment]
Ouch, that's right... I'll take a look as soon as I can.

Thanks!

**Comment by nuzza412** [comment]
No prob! Thank you!

**Comment by nuzza412** [comment]
The same error is displayed if you try to download the sounds :(
